name: glashelderdesign.nl
favicon: null
layout_spectrum: 0.99932
typography_spectrum: 0.23998
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b7689'
    - '#ffffff'
    - '#0066b3'
    - '#3d3d3c'
    - '#ced2d6'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
