favicon: null
name: glashelderdesign.nl
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.0625
  brandStrength: 0.625
  rhythmicContrast: 0
  brandColors:
    - '#6b7688'
    - '#205fae'
    - '#58c9eb'
    - '#ffffff'
    - '#b2c5de'
  lightness: 0.75
typography_spectrum: 0.4795918
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.99932
analytics:
  twitter: null
  google: null
  facebook: null
